### ISSUE TITLE
Cant run a modpack due to some errors 

### ISSUE THREAD

**Issue by gog282** [Kasax007/Dreamcraft-Development-#78]
Cant run a modpack:

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config cloth-client-events-v0.mixins.json for mod cloth-client-events-v0
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config cloth-client-events-v0.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'cloth-client-events-v0.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by Kasax007** [comment]
Can you send the full latest.log and let me know:
What operating system are you on? 
What version of the pack?

**Comment by Kasax007** [comment]
Closed due to inactivity. If the issue persists feel free to reopen the issue.
