### ISSUE TITLE
creative worldshaper crashes

### ISSUE THREAD

**Issue by Giro100** [Kasax007/Dreamcraft-Development-#84]
**Describe the bug**
creative worldshaper crashes the game

**To Reproduce**
1. put the creative worldshaper in the main hand
2. Click on a grass block or try to build with it
4. game crashed and closed

**Expected behavior**
i can activate the item so i dont know what suppose to happen

**Screenshots + Crash log**
added crash log

**Version of the modpack**
fabric v6

**Additional context**
multiplayer and single words crashes client side

[crash-2023-02-02_21.42.48-client.txt](https://github.com/Kasax007/Modpack-Development/files/10572837/crash-2023-02-02_21.42.48-client.txt)

**Comment by Kasax007** [comment]
Can you build with another block? When I was testing it worked for me. I think it only occurs because of the vision rendering engine and a better grass mod. You can try and remove that. (Lambda better grass). 

at dev.lambdaurora.lambdabettergrass.model.LBGBakedModel.emitItemQuads(LBGBakedModel.java:167)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111)
